/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author sainp
 */
public class Login_Form extends javax.swing.JFrame {

    /**
     * Creates new form Login_Form
     */
    public Login_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        Usuario = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        Rol = new javax.swing.JLabel();
        comboRol = new javax.swing.JComboBox<>();
        btnLogin = new javax.swing.JButton();
        Registro = new javax.swing.JLabel();
        Olvido = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        chkMostrar = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelFondo.setBackground(new java.awt.Color(0, 119, 182));
        panelFondo.setForeground(new java.awt.Color(255, 255, 255));
        panelFondo.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/Logo Samval (100 x 100 px).png"))); // NOI18N
        jLabel3.setText("jLabel3");
        panelFondo.add(jLabel3);
        jLabel3.setBounds(70, 20, 100, 110);

        txtUsuario.setColumns(20);
        txtUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 41, 77));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        panelFondo.add(txtUsuario);
        txtUsuario.setBounds(180, 60, 210, 40);

        Usuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Usuario.setText("Usuario");
        panelFondo.add(Usuario);
        Usuario.setBounds(190, 40, 70, 20);

        Contraseña.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        Contraseña.setText("Contraseña");
        panelFondo.add(Contraseña);
        Contraseña.setBounds(160, 160, 120, 22);

        txtPassword.setColumns(20);
        txtPassword.setForeground(new java.awt.Color(0, 41, 77));
        txtPassword.setText("jPasswordField1");
        panelFondo.add(txtPassword);
        txtPassword.setBounds(160, 180, 170, 26);

        Rol.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Rol.setForeground(new java.awt.Color(255, 255, 255));
        Rol.setText("Rol");
        panelFondo.add(Rol);
        Rol.setBounds(330, 240, 30, 17);

        comboRol.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        comboRol.setForeground(new java.awt.Color(0, 41, 77));
        comboRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Empleado" }));
        panelFondo.add(comboRol);
        comboRol.setBounds(320, 260, 200, 28);

        btnLogin.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        panelFondo.add(btnLogin);
        btnLogin.setBounds(150, 300, 130, 37);

        Registro.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        Registro.setForeground(new java.awt.Color(255, 255, 255));
        Registro.setText("¿No tienes cuenta? Regístrate");
        panelFondo.add(Registro);
        Registro.setBounds(170, 110, 270, 20);

        Olvido.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Olvido.setForeground(new java.awt.Color(255, 255, 255));
        Olvido.setText("¿Olvidaste tu contraseña?");
        panelFondo.add(Olvido);
        Olvido.setBounds(160, 210, 150, 20);

        Regresar.setBackground(new java.awt.Color(0, 41, 77));
        Regresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Regresar.setForeground(new java.awt.Color(0, 41, 77));
        Regresar.setText("Regresar");
        panelFondo.add(Regresar);
        Regresar.setBounds(70, 390, 110, 25);

        chkMostrar.setFont(new java.awt.Font("Arial", 3, 18)); // NOI18N
        chkMostrar.setText("Mostrar contraseña");
        chkMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMostrarActionPerformed(evt);
            }
        });
        panelFondo.add(chkMostrar);
        chkMostrar.setBounds(360, 180, 220, 31);

        getContentPane().add(panelFondo);
        panelFondo.setBounds(0, 0, 670, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
String usuario = txtUsuario.getText();
String password = new String(txtPassword.getPassword());
String rol = comboRol.getSelectedItem().toString();

try {
    Connection con = modelo.Conexion_DB.getConnection();
    PreparedStatement ps = con.prepareStatement(
        "SELECT * FROM usuarios WHERE Email_Usuario=? AND Contraseña_Usuario=? AND Rol_Usuario=?"
    );

    ps.setString(1, usuario);
    ps.setString(2, password);
    ps.setString(3, rol);

    ResultSet rs = ps.executeQuery();

    if (rs.next()) {
        String nombre = rs.getString("Nombre_Usuario");
        JOptionPane.showMessageDialog(this, "✅ Acceso permitido. ¡Bienvenido, " + nombre + "!");
    } else {
        JOptionPane.showMessageDialog(this, "❌ Acceso denegado. Verifica los datos.");
    }

    con.close();

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "⚠️ Error: " + e.getMessage());
}

    

    }//GEN-LAST:event_btnLoginActionPerformed

    private void chkMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMostrarActionPerformed
                                                  
    if (chkMostrar.isSelected()) {
        txtPassword.setEchoChar((char) 0); // Muestra la contraseña
    } else {
        txtPassword.setEchoChar('●'); // Oculta con bolitas o asteriscos
    }


    }//GEN-LAST:event_chkMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel Olvido;
    private javax.swing.JLabel Registro;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel Rol;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox chkMostrar;
    private javax.swing.JComboBox<String> comboRol;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
